Напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [24]:
from sklearn.linear_model import LinearRegression

def linear_regression_hypothesis(X, w):
    pass

model = LinearRegression()
model.fit(X, y)

predictions = model.predict(X)
predictions

array([ 7036627.15462756, 10392020.79073061,  7591864.51496454,
        7066928.17491437,  5650577.65683656,  8046157.63893618,
        8862041.44657728, 12155033.66266496,  5908136.32927443,
        5997273.32237125,  7433006.33878929,  7884833.54232771,
        6707103.55900852,  5551877.16057395,  6773736.96722072,
        5112734.54674571,  6726041.69668777,  7038870.89473029,
        5561696.15574838,  6251044.36727327,  4069593.08695356,
        6529434.99115833,  5482378.157826  ,  5546545.64560498,
        7152499.72080582,  6703315.93147267,  6091964.01076753,
        5794857.42953371,  7644191.44779685,  6309402.66774416,
        6650639.07230556,  5084677.26656164,  6074569.76052139,
        7462862.99841512,  5837715.29352638,  6470726.76435263,
        6653290.41158065,  7635072.30529203,  4705914.51297653,
        6498784.04453671,  4914234.02744834,  6228318.60205817,
        6273770.13248838,  6498784.04453671,  6498784.04453671,
        6091964.01076753,  6091964.01076

Створіть функцію для обчислення функції втрат у векторному вигляді;

In [29]:
from sklearn.metrics import mean_squared_error

def compute_cost(predictions, y):
    cost = mean_squared_error(y, predictions) / 2.0
    return cost

Реалізуйте один крок градієнтного спуску;

In [34]:
model.fit(X, y)

LinearRegression()

Знайдіть найкращі параметри $\vec{w}$ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [35]:
# Датасет
import gdown
import pandas as pd
file_id = '1-rAa4XT4_fI0dOBlMNuE6a7jB0wln_Qo'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'dataset.csv'
gdown.download(url, output, quiet=False)

df = pd.read_csv('dataset.csv')
print(df.head())
X = df[['area', 'bathrooms', 'bedrooms']]
y = df['price']
print("X:")
print(X.head())
print("\ny:")
print(y.head())


Downloading...
From: https://drive.google.com/uc?id=1-rAa4XT4_fI0dOBlMNuE6a7jB0wln_Qo
To: /content/dataset.csv
100%|██████████| 30.0k/30.0k [00:00<00:00, 45.2MB/s]

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
X:
   area  bathrooms  bedrooms
0  7420          2         4
1  8960          4         4
2  9960  

In [36]:
model.fit(X, y)
w_sklearn = np.append(model.intercept_, model.coef_)
w_sklearn

array([-1.73171608e+05,  3.78762754e+02,  1.38604950e+06,  4.06820034e+05])

Знайдіть ці ж параметри за допомогою аналітичного рішення;

In [32]:
X_extended = np.c_[np.ones((len(X), 1)), X]
w_analytical = np.linalg.inv(X_extended.T @ X_extended) @ X_extended.T @ y
w_analytical

array([-1.73171608e+05,  3.78762754e+02,  1.38604950e+06,  4.06820034e+05])

Порівняйте отримані результати

In [33]:
print("Parameters (scikit-learn):", w_sklearn)
print("Parameters (analytical solution):", w_analytical)

# Прогнози та втрати
predictions_sklearn = model.predict(X)
predictions_analytical = np.dot(X_extended, w_analytical)

cost_sklearn = compute_cost(predictions_sklearn, y)
cost_analytical = compute_cost(predictions_analytical, y)

print("Cost (scikit-learn):", cost_sklearn)
print("Cost (analytical solution):", cost_analytical)

Parameters (scikit-learn): [-1.73171608e+05  3.78762754e+02  1.38604950e+06  4.06820034e+05]
Parameters (analytical solution): [-1.73171608e+05  3.78762754e+02  1.38604950e+06  4.06820034e+05]
Cost (scikit-learn): 895585024988.6595
Cost (analytical solution): 895585024988.6597
